// <auto-generated />
using System;
using App.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace App.Web.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("App.Base.Entities.AppClient", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("ClientName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CurrentVersion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsMobileBankingClient")
                        .HasColumnType("bit");

                    b.Property<string>("Link")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("app_client");
                });

            modelBuilder.Entity("App.Base.Entities.TaskType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<long>("RecById")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("RecDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("RecStatus")
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("TaskTypeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("RecById");

                    b.ToTable("TaskTypes");
                });

            modelBuilder.Entity("App.Base.Entities.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IsAdmin")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("IsNewPassword")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RecBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RecDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("RecStatus")
                        .HasColumnType("nvarchar(1)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("App.CloudTask.Entity.CloudTask", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("ClientId")
                        .HasColumnType("bigint");

                    b.Property<string>("CloudUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CompleteTime")
                        .HasColumnType("datetime2");

                    b.Property<long?>("CompletedById")
                        .HasColumnType("bigint");

                    b.Property<string>("IssueOnPreviousSoftware")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LicDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Priority")
                        .HasColumnType("nvarchar(1)");

                    b.Property<long?>("ProccedById")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("ProccedTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("RecAuditLog")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("RecById")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("RecDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("RecStatus")
                        .HasColumnType("nvarchar(1)");

                    b.Property<int>("RecVersion")
                        .HasColumnType("int");

                    b.Property<string>("Remarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoftwareVersionFrom")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoftwareVersionTo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TSKStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TaskName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TaskTime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TaskTypeId")
                        .HasColumnType("int");

                    b.Property<int?>("TelegramMessageId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("CompletedById");

                    b.HasIndex("ProccedById");

                    b.HasIndex("RecById");

                    b.HasIndex("TaskTypeId");

                    b.ToTable("CloudTasks");
                });

            modelBuilder.Entity("App.CloudTask.Entity.CloudTaskLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<long>("CloudTaskId")
                        .HasColumnType("bigint");

                    b.Property<int?>("CloudTaskId1")
                        .HasColumnType("int");

                    b.Property<string>("CloudTaskStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RecDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Remarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CloudTaskId");

                    b.HasIndex("CloudTaskId1");

                    b.HasIndex("UserId");

                    b.ToTable("CloudTasksLog");
                });

            modelBuilder.Entity("App.Base.Entities.TaskType", b =>
                {
                    b.HasOne("App.Base.Entities.User", "RecBy")
                        .WithMany()
                        .HasForeignKey("RecById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RecBy");
                });

            modelBuilder.Entity("App.CloudTask.Entity.CloudTask", b =>
                {
                    b.HasOne("App.Base.Entities.AppClient", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("App.Base.Entities.User", "CompletedBy")
                        .WithMany()
                        .HasForeignKey("CompletedById")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("App.Base.Entities.User", "ProccedBy")
                        .WithMany()
                        .HasForeignKey("ProccedById")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("App.Base.Entities.User", "RecBy")
                        .WithMany()
                        .HasForeignKey("RecById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("App.Base.Entities.TaskType", "TaskType")
                        .WithMany()
                        .HasForeignKey("TaskTypeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("CompletedBy");

                    b.Navigation("ProccedBy");

                    b.Navigation("RecBy");

                    b.Navigation("TaskType");
                });

            modelBuilder.Entity("App.CloudTask.Entity.CloudTaskLog", b =>
                {
                    b.HasOne("App.CloudTask.Entity.CloudTask", null)
                        .WithMany("CloudTaskLogs")
                        .HasForeignKey("CloudTaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("App.CloudTask.Entity.CloudTaskLog", "CloudTask")
                        .WithMany()
                        .HasForeignKey("CloudTaskId1");

                    b.HasOne("App.Base.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("CloudTask");

                    b.Navigation("User");
                });

            modelBuilder.Entity("App.CloudTask.Entity.CloudTask", b =>
                {
                    b.Navigation("CloudTaskLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
